# Generated by Django 5.0.7 on 2024-07-25 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0002_region_tipoinmueble_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='arrendador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arriendos.usuario'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='precio_arriendo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_inmueble',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela')], default='casa', max_length=12),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('arrendatario', 'Arrendatario'), ('arrendador', 'Arrendador')], default='arrendatario', max_length=12),
        ),
    ]
