# Generated by Django 5.0.7 on 2024-07-25 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0003_propiedad_arrendador_propiedad_precio_arriendo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arriendos.comuna'),
        ),
    ]
